apiVersion: v2
name: multiwoven
description: Open-source reverse ETL, an alternative to Hightouch, Census etc. ðŸ”¥
type: application
version: 0.50.0
appVersion: "050.0"
maintainers:
  - name: subintp
  - name: RafaelOAiSquared
  - name: AngeloB-AIS
