{{- if .Values.lightning.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-lightning
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lightning.type }}
  selector:
    io.kompose.service: {{ include "chart.fullname" . }}-lightning
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.lightning.ports | nindent 4 }}
{{- end }}
