{{ if .Values.lightening.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-lightening
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    io.kompose.service: {{ include "chart.fullname" . }}-lightening
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lightening.type }}
  selector:
    io.kompose.service: {{ include "chart.fullname" . }}-lightening
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	  {{- .Values.lightening.ports | toYaml | nindent 2 -}}
{{ end }}