{{ if .Values.lightening.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-lightening
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
    io.kompose.service: {{ include "chart.fullname" . }}-lightening
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.lightening.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.lightening.replicas }}
  selector:
    matchLabels:
      io.kompose.service: {{ include "chart.fullname" . }}-lightening
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/multiwoven-server-default: "true"
        io.kompose.service: {{ include "chart.fullname" . }}-lightening
      {{- include "chart.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.lightening.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - env:
        - name: VERSION
          value: {{ .Values.lighteningConfig.version | quote}}
        - name: HF_TOKEN
          value: {{ .Values.lighteningConfig.hfToken | quote }}
        - name: HUGGINGFACE_BILLING_ACCOUNT
          value: {{ .Values.lighteningConfig.hfBillingAccount | quote }}
        - name: NANONETS_API_KEY
          value: {{ .Values.lighteningConfig.nanonetsApiKey | quote }}
        image: {{ .Values.lightening.lightening.image.repository }}:{{ .Values.lightening.lightening.image.tag | default .Chart.AppVersion }}
        args: {{- toYaml .Values.lightening.lightening.args | nindent 10 }}
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 6000
        name: {{ include "chart.fullname" . }}-lightening
        ports:
        - containerPort: 6000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 6000
        resources: {{- toYaml .Values.lightening.lightening.resources | nindent 10 }}
      restartPolicy: Always
      {{ if .Values.multiwovenConfig.privateRepo }}
      imagePullSecrets:
        - name: {{ .Values.multiwovenConfig.registrySecretName }}
      {{ end }}
{{ end }}