apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ui-ingress
  namespace: {{ .Values.kubernetesNamespace }}

  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    
spec:
  rules:
#   - host:  {{ .Values.multiwovenConfig.uiHost }}
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-ui'
            port:
              number: 8000
        path: /
        pathType: Prefix