apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-server
  namespace: {{ .Values.kubernetesNamespace }}

  labels:
    io.kompose.service:  {{ include "chart.fullname" . }}-server
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
spec:
  type: {{ .Values.aisquaredServer.type }}
  selector:
    io.kompose.service:  {{ include "chart.fullname" . }}-server
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.aisquaredServer.ports | toYaml | nindent 2 -}}